disabled_rules:
  - block_based_kvo
  - force_cast
  - force_try
  - function_parameter_count
  - identifier_name
  - large_tuple
  - notification_center_detachment
  - todo
  - trailing_comma
  - trailing_whitespace
  - type_name
  - vertical_parameter_alignment
  - vertical_whitespace
  - weak_delegate
excluded:
  - dependencies
  - target/
  - vendor/
  - Pods/
  - docs/
  - Derived/
  - Frameworks/*/Derived/
  - Frameworks/*/Playgrounds/
  - lib/scripts/sc-mover/Tests/Fixtures/
  - path/
line_length: 500
type_body_length:
  - 300 # warning
  - 400 # error
file_length:
  warning: 500
  error: 1200
function_body_length: 45
nesting:
  type_level: 3

